Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y python3 python3-pip libpq-dev
    pip3 install psycopg2-binary django
  SHELL

  # Путь к пустому файлу на вашем ПК
  config.vm.synced_folder ".", "/vagrant", type: "virtualbox"

  # Копирование пустого файла в файловую систему ВМ
  config.vm.provision "file", source: "../empty.txt", destination: "~/empty.txt"
end

